language: node_js
sudo: true
cache:
  apt: true
  directories: 
    - node_modules

node_js: 
  - "14"

install:
  - sudo apt install nasm
  - npm install 

script:
  - npm test

branches:
  only:
  - master